[versions]
agp = "9.2.1"
appcompat = "1.4.2" # seems to be the last version that supports minSdk 16

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
